I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 396, in script call
    call chooseActions
  File "game/script.rpy", line 402, in script
    python:
  File "game/script.rpy", line 406, in <module>
    action[x] = int(chooseSkill(player[x]))
  File "game/script.rpy", line 24, in chooseSkill
    while skillsInMenu != len(skillList):
NameError: global name 'skillList' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 396, in script call
    call chooseActions
  File "game/script.rpy", line 402, in script
    python:
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 406, in <module>
    action[x] = int(chooseSkill(player[x]))
  File "game/script.rpy", line 24, in chooseSkill
    while skillsInMenu != len(skillList):
NameError: global name 'skillList' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
Breached Macrocosms 1.0
Thu May 26 14:49:16 2022
